### ISSUE TITLE
Issue with the title screen

### ISSUE THREAD

**Issue by Zenith2557** [PaleCourt/PaleCourt#25]
It seems that most if not all of the animated elements of the Pale Court title screen are just displayed as pink squares. Not a huge deal ofc, but I would love to see it in its full glory! Keep up the great work <3
<img width="654" alt="Screen Shot 2023-07-02 at 7 19 10 PM" src="https://github.com/PaleCourt/PaleCourt/assets/138417056/c1438d73-76ac-4ed3-bfe5-e26018b6f14e">

**Comment by CausticWarrior** [comment]
Its for the other sprites too, be warned!

**Comment by SalehAce1** [comment]
Mod was incompatible with Mac and Linux but that was fixed in version 1.0.1.0

**Comment by jh-devv** [comment]
this seems to be still occuring
somehow steam locks the game to use proton and you have to use https://github.com/Scrumplex/Steam-Play-None at least on the steam deck!
^-^

**Comment by sidjmt** [comment]
> this seems to be still occuring
> somehow steam locks the game to use proton and you have to use https://github.com/Scrumplex/Steam-Play-None at least on the steam deck!
> ^-^

@jh-devv this worked for me on steam deck!  After switching to none, Steam removed my mods, but I used scarab to reinstall and everything was good after that.  Thanks!
